# Generated by Django 6.0.1 on 2026-01-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=200)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
